# Generated by Django 3.2.19 on 2024-01-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_remarks_catalog_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='working_hours',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
