# Generated by Django 3.2.19 on 2024-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_working_hours_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_hours',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='working_hours',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
