# Generated by Django 3.2.19 on 2024-01-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20240128_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='business_cover_pic',
            field=models.ImageField(default=1, upload_to='media/business_cover_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='business_logo',
            field=models.ImageField(default=1, upload_to='media/business_logo'),
            preserve_default=False,
        ),
    ]
