# Generated by Django 3.2.19 on 2024-01-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20240128_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='business_cover_pic',
            field=models.ImageField(blank=True, default='business_cover_pics/to/default/no-image.png', null=True, upload_to='business_cover_pics/'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='business_logo',
            field=models.ImageField(blank=True, default='business_logo/to/default/no-profile-picture.png', null=True, upload_to='business_logo/'),
        ),
    ]
