# Generated by Django 3.2.19 on 2024-01-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20240128_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_appointment_catalog', to='business.appointment'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='working_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_working_hours_catalog', to='business.working_hours'),
        ),
    ]
