# Generated by Django 3.2.19 on 2024-01-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_working_hours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_hours',
            name='closed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
